### ISSUE TITLE
Source directory and destination directory cannot be identical

### ISSUE THREAD

**Issue by Stolb27** [dusktreader/sphinx-view#33]
https://github.com/dusktreader/sphinx-view/blob/28770b984f7270de287b9d16c42c45e06a769108/sview/builder.py#L213

https://github.com/sphinx-doc/sphinx/blob/dc0120be358de037daf7d76d8b8bc218a089d1b0/sphinx/application.py#L159

**Comment by jougs** [comment]
This is the same issue as https://github.com/sphinx-doc/sphinx/issues/5427. I've filed a [PR fixing this](33)

**Comment by CarlAndersson** [comment]
Is there any progress on this issue? Any possible workarounds in the meantime?

**Comment by jougs** [comment]
As far as I can judge, the branch #34 is based on works just fine and in principle fixes the problem. The only reason the tests are still failing there is the test setup in Travis. As I since moved to using plain sphinx I did not take the time to work further on getting it to run properly.

**Comment by dusktreader** [comment]
I'm sorry for the long, long delay in addressing this. Has been fixed in PR #35
